sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x .travis-ssh.sh
script:
  - ./.travis-ssh.sh
  - ./gradlew mirakle:build mirakle:install plugin-test:test
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'
os:
  - linux
